stages:
  - generate
  - publish

workflow:
  rules:
    - if: '($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_COMMIT_BRANCH == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'
      when: always
    - if: '$FORCE_PIPELINE == "true"'
      when: always
    - when: never

# TODO: check breaking

buf_generate:
  stage: generate
  image:
    name: nixos/nix
  before_script:
    - cat $NETRC > $HOME/.netrc
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
  script:
    - nix-shell --command 'buf generate'
  artifacts:
    paths:
      - pb
    expire_in: 1 day

publish_genproto_github:
  stage: publish
  image:
    name: alpine
  variables:
    # Skip host key verification prompt
    GIT_SSH_COMMAND: "/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
    GIT_AUTHOR_NAME: "Innovation Upstream Bot"
    GIT_AUTHOR_EMAIL: "zach+ci@innovationupstream.com"
    GIT_COMMITTER_NAME: "Innovation Upstream Bot"
    GIT_COMMITTER_EMAIL: "zach+ci@innovationupstream.com"
  before_script:
    - apk update && apk add git openssh
    - \[ -d ~/.ssh \] || mkdir ~/.ssh
    - |-
      cat <<EOT >> ~/.ssh/config
      Host github.com-innovation-upstream-iu-proto
        Hostname github.com
        IdentityFile=$GITHUB_IU_PROTO_DEPLOY_SSH_KEY_PRIVATE
      EOT
    - chmod 0600 $GITHUB_IU_PROTO_DEPLOY_SSH_KEY_PRIVATE
  script:
    - mv pb/go.innovationupstream.dev/go-genproto downstream
    - cd downstream/go-genproto
    - git init --initial-branch main
    - git remote add origin git@github.com-innovation-upstream-iu-proto:innovation-upstream/go-genproto.git
    - git pull origin main
    - git add .
    - git commit -m "$CI_COMMIT_MESSAGE"
    - git push -u origin main
  needs:
    - buf_generate

publish_bsr:
  stage: publish
  image:
    name: bufbuild/buf
    entrypoint: [""]
  variables:
    BUF_TOKEN: $BSR_API_TOKEN
  script:
    - buf push

