stages:
  - generate
  - publish

workflow:
  rules:
    - if: '($CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event") && ($CI_COMMIT_BRANCH == "main" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")'
      when: always
    - if: '$FORCE_PIPELINE == "true"'
      when: always
    - when: never

# TODO: check breaking

buf_generate:
  stage: generate
  image:
    name: nixos/nix
  before_script:
    - cat $NETRC > $HOME/.netrc
    - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
    - nix-channel --update
  script:
    - nix-shell --command 'buf generate'
  artifacts:
    paths:
      - pb
    expire_in: 1 day

publish_genproto_github:
  stage: publish
  image:
    name: ubuntu
  variables:
    # Skip host key verification prompt
    GIT_SSH_COMMAND: "/usr/bin/ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  before_script:
    - apt update && apt install -y git
    - \[ -d ~/.ssh \] || mkdir ~/.ssh
    - |-
      cat <<EOT >> ~/.ssh/config
      Host github.com-innovation-upstream-iu-proto
        Hostname github.com
        IdentityFile=$GITHUB_IU_PROTO_DEPLOY_SSH_KEY_PRIVATE
      EOT
  script:
    - mv pb/go.innovationupstream.dev/go-genproto downstream
    - cd downstream/go-genproto
    - git init
    - git remote add origin git@github.com-innovation-upstream-iu-proto:innovation-upstream/go-genproto.git
    - git pull
    - git checkout main
    - git commit -m $CI_COMMIT_MESSAGE
    - git push
  needs:
    - buf_generate

publish_bsr:
  stage: publish
  image:
    name: bufbuild/buf
    entrypoint: ["/bin/sh"]
  before_script:
    - \[ -d ~/.ssh \] || mkdir ~/.ssh
    - |-
      cat <<EOT >> ~/.netrc
      machine buf.build
      login zachlowden1@gmail.com
      password $BSR_API_TOKEN
      EOT
  script:
    - buf push

